# command: python train_her.py --diff 3 --lr 7.3e-4 --n_steps 4e5 \  
# --rew_fn train5 --name contact-0g-diff3 --contact --seed 1 

name: contact_diff3_runs
program: train_sb3.py
method: grid
project: cvxrl
metric:
  name: rollout/ep_rew_mean
  goal: maximize
parameters:
  seed:
    distribution: categorical
    values: [0, 1, 2]
  lr:
    value: 7.3e-4
  n_steps:
    value: 4e5
  rew_fn:
    value: 'train5'
  diff:
    value: 3
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - "--contact"
